import {
  DEFAULT_SEMANTIC_TOKENS,
  SEMANTIC_TOKEN_KEYS,
  type SemanticTokens,
} from "./semantic-tokens";

export const SEMANTIC_THEME_PRESET_IDS = [
  "default",
  "ocean",
  "forest",
  "charcoal",
  "violet",
  "sunset",
  "midnight",
  "lilac",
  "slate",
  "neon",
] as const;

export type SemanticThemePresetId = (typeof SEMANTIC_THEME_PRESET_IDS)[number];

export interface SemanticThemePreset {
  id: SemanticThemePresetId;
  labelKey: string;
  tokens: SemanticTokens;
}

export const SEMANTIC_THEME_PRESETS: readonly SemanticThemePreset[] = [
  {
    id: "default",
    labelKey: "semanticPresets.default",
    tokens: DEFAULT_SEMANTIC_TOKENS,
  },
  {
    id: "ocean",
    labelKey: "semanticPresets.ocean",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#0a2a43",
      "card-foreground": "#0a2a43",
      "popover-foreground": "#0a2a43",
      "secondary-foreground": "#0a2a43",
      "accent-foreground": "#0a2a43",
      primary: "#1e6fbf",
      "primary-foreground": "#f8fbff",
      ring: "#1e6fbf",
      "sidebar-foreground": "#0a2a43",
      "sidebar-primary": "#1e6fbf",
      "sidebar-accent-foreground": "#0a2a43",
      background: "#f4f9ff",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#e8f2fb",
      muted: "#e8f2fb",
      accent: "#dceaf7",
      border: "#c5d9ee",
      input: "#c5d9ee",
      success: "#1f7a5c",
      warning: "#d9a441",
      "warning-foreground": "#3d2e10",
    },
  },
  {
    id: "forest",
    labelKey: "semanticPresets.forest",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#1f3d2f",
      "card-foreground": "#1f3d2f",
      "popover-foreground": "#1f3d2f",
      "secondary-foreground": "#1f3d2f",
      "accent-foreground": "#1f3d2f",
      primary: "#2f7d57",
      "primary-foreground": "#f5fff9",
      ring: "#2f7d57",
      "sidebar-foreground": "#1f3d2f",
      "sidebar-primary": "#2f7d57",
      "sidebar-accent-foreground": "#1f3d2f",
      background: "#f7fbf8",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#e8f3ec",
      muted: "#e8f3ec",
      accent: "#dceee3",
      border: "#c6ddd0",
      input: "#c6ddd0",
      success: "#2f7d57",
      warning: "#c9a227",
      "warning-foreground": "#3d3010",
      "star-gold": "#c9a227",
      "surface-warm": "#f9fbf6",
    },
  },
  {
    id: "charcoal",
    labelKey: "semanticPresets.charcoal",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#1f2937",
      "card-foreground": "#1f2937",
      "popover-foreground": "#1f2937",
      "secondary-foreground": "#1f2937",
      "accent-foreground": "#1f2937",
      primary: "#374151",
      "primary-foreground": "#f9fafb",
      ring: "#4b5563",
      "sidebar-foreground": "#1f2937",
      "sidebar-primary": "#374151",
      "sidebar-accent-foreground": "#1f2937",
      background: "#f9fafb",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#f3f4f6",
      muted: "#f3f4f6",
      accent: "#e5e7eb",
      border: "#d1d5db",
      input: "#d1d5db",
      destructive: "#dc2626",
      success: "#15803d",
      warning: "#ca8a04",
      "warning-foreground": "#422006",
      "chart-1": "#d1d5db",
      "chart-2": "#9ca3af",
      "chart-3": "#6b7280",
      "chart-4": "#4b5563",
      "chart-5": "#374151",
    },
  },
  {
    id: "violet",
    labelKey: "semanticPresets.violet",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#2a1f47",
      "card-foreground": "#2a1f47",
      "popover-foreground": "#2a1f47",
      "secondary-foreground": "#2a1f47",
      "accent-foreground": "#2a1f47",
      primary: "#6d28d9",
      "primary-foreground": "#faf5ff",
      ring: "#6d28d9",
      "sidebar-foreground": "#2a1f47",
      "sidebar-primary": "#6d28d9",
      "sidebar-accent-foreground": "#2a1f47",
      background: "#faf7ff",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#f1e9ff",
      muted: "#f1e9ff",
      accent: "#e9ddff",
      border: "#d8c4f5",
      input: "#d8c4f5",
      success: "#2f7d57",
      warning: "#d97706",
      "warning-foreground": "#431407",
      "rank-cosmic": "#3b1f6e",
    },
  },
  {
    id: "sunset",
    labelKey: "semanticPresets.sunset",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#3d2314",
      "card-foreground": "#3d2314",
      "popover-foreground": "#3d2314",
      "secondary-foreground": "#3d2314",
      "accent-foreground": "#3d2314",
      primary: "#c45c3e",
      "primary-foreground": "#fff7f2",
      ring: "#c45c3e",
      "sidebar-foreground": "#3d2314",
      "sidebar-primary": "#c45c3e",
      "sidebar-accent-foreground": "#3d2314",
      background: "#fdf6f0",
      card: "#fffaf6",
      popover: "#fffaf6",
      secondary: "#f6e6d8",
      muted: "#f6e6d8",
      "muted-foreground": "#8a5a42",
      accent: "#f0d0c4",
      border: "#e8cbb8",
      input: "#e8cbb8",
      destructive: "#c2410c",
      success: "#3d8a5a",
      warning: "#e09a3e",
      "warning-foreground": "#3d2a10",
      sidebar: "#fff7f2",
      "sidebar-accent": "#f6e6d8",
      "sidebar-border": "#e8cbb8",
      "chart-1": "#e8cbb8",
      "chart-2": "#c45c3e",
      "chart-3": "#d4786a",
      "chart-4": "#8a5a42",
      "chart-5": "#3d2314",
      "star-gold": "#d4a017",
      "star-gold-muted": "#f8ead4",
      "surface-warm": "#fff4ea",
      "rank-cosmic": "#4a2030",
    },
  },
  {
    id: "midnight",
    labelKey: "semanticPresets.midnight",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#e2e8f0",
      "card-foreground": "#e2e8f0",
      "popover-foreground": "#e2e8f0",
      "secondary-foreground": "#e2e8f0",
      "accent-foreground": "#e2e8f0",
      primary: "#22d3ee",
      "primary-foreground": "#0f172a",
      ring: "#22d3ee",
      "sidebar-foreground": "#e2e8f0",
      "sidebar-primary": "#22d3ee",
      "sidebar-primary-foreground": "#0f172a",
      "sidebar-accent-foreground": "#e2e8f0",
      background: "#0f172a",
      card: "#1e293b",
      popover: "#1e293b",
      secondary: "#1e293b",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#164e63",
      border: "#334155",
      input: "#334155",
      overlay: "#000000",
      destructive: "#f87171",
      "destructive-foreground": "#fafafa",
      success: "#34d399",
      "success-foreground": "#064e3b",
      warning: "#fbbf24",
      "warning-foreground": "#422006",
      sidebar: "#020617",
      "sidebar-accent": "#1e293b",
      "sidebar-border": "#334155",
      "sidebar-ring": "#22d3ee",
      "chart-1": "#334155",
      "chart-2": "#64748b",
      "chart-3": "#22d3ee",
      "chart-4": "#38bdf8",
      "chart-5": "#e2e8f0",
      "star-gold": "#fbbf24",
      "star-gold-foreground": "#422006",
      "star-gold-muted": "#1e293b",
      "surface-warm": "#1e293b",
      "rank-cosmic": "#020617",
    },
  },
  {
    id: "lilac",
    labelKey: "semanticPresets.lilac",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#3b1f5e",
      "card-foreground": "#3b1f5e",
      "popover-foreground": "#3b1f5e",
      "secondary-foreground": "#3b1f5e",
      "accent-foreground": "#3b1f5e",
      primary: "#7c5cbf",
      "primary-foreground": "#fdfbf7",
      ring: "#7c5cbf",
      "sidebar-foreground": "#3b1f5e",
      "sidebar-primary": "#7c5cbf",
      "sidebar-accent-foreground": "#3b1f5e",
      background: "#fdfbf7",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#f3eef8",
      muted: "#f3eef8",
      "muted-foreground": "#7a6a8c",
      accent: "#e9dff5",
      border: "#ddd0e8",
      input: "#ddd0e8",
      success: "#4d8f72",
      warning: "#c9a227",
      "warning-foreground": "#3d3010",
      sidebar: "#faf7ff",
      "sidebar-accent": "#f3eef8",
      "sidebar-border": "#ddd0e8",
      "chart-1": "#ddd0e8",
      "chart-2": "#c4b0e0",
      "chart-3": "#7c5cbf",
      "chart-4": "#5b3d99",
      "chart-5": "#3b1f5e",
      "star-gold": "#b8a06a",
      "star-gold-muted": "#f6f0e4",
      "surface-warm": "#fdfbf7",
      "rank-cosmic": "#3b1f5e",
    },
  },
  {
    id: "slate",
    labelKey: "semanticPresets.slate",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#171717",
      "card-foreground": "#171717",
      "popover-foreground": "#171717",
      "secondary-foreground": "#171717",
      "accent-foreground": "#171717",
      primary: "#262626",
      "primary-foreground": "#fafafa",
      ring: "#404040",
      "sidebar-foreground": "#171717",
      "sidebar-primary": "#262626",
      "sidebar-accent-foreground": "#171717",
      background: "#ffffff",
      card: "#ffffff",
      popover: "#ffffff",
      secondary: "#f5f5f5",
      muted: "#f5f5f5",
      accent: "#e5e5e5",
      border: "#e5e5e5",
      input: "#e5e5e5",
      destructive: "#dc2626",
      success: "#3f6b54",
      warning: "#737373",
      "warning-foreground": "#171717",
      sidebar: "#fafafa",
      "sidebar-accent": "#f5f5f5",
      "sidebar-border": "#e5e5e5",
      "sidebar-ring": "#a3a3a3",
      "chart-1": "#e5e5e5",
      "chart-2": "#a3a3a3",
      "chart-3": "#737373",
      "chart-4": "#525252",
      "chart-5": "#262626",
      "star-gold": "#525252",
      "star-gold-foreground": "#fafafa",
      "star-gold-muted": "#f5f5f5",
      "surface-warm": "#fafafa",
      "rank-cosmic": "#171717",
    },
  },
  {
    id: "neon",
    labelKey: "semanticPresets.neon",
    tokens: {
      ...DEFAULT_SEMANTIC_TOKENS,
      foreground: "#f5f3ff",
      "card-foreground": "#f5f3ff",
      "popover-foreground": "#f5f3ff",
      "secondary-foreground": "#f5f3ff",
      "accent-foreground": "#f5f3ff",
      primary: "#d946ef",
      "primary-foreground": "#f5f3ff",
      ring: "#a3e635",
      "sidebar-foreground": "#f5f3ff",
      "sidebar-primary": "#d946ef",
      "sidebar-primary-foreground": "#f5f3ff",
      "sidebar-accent-foreground": "#f5f3ff",
      background: "#0c0614",
      card: "#160b24",
      popover: "#160b24",
      secondary: "#1a0b2e",
      muted: "#1a0b2e",
      "muted-foreground": "#c4b5fd",
      accent: "#2e1065",
      border: "#6b21a8",
      input: "#6b21a8",
      overlay: "#000000",
      destructive: "#fb7185",
      "destructive-foreground": "#fafafa",
      success: "#a3e635",
      "success-foreground": "#14532d",
      warning: "#22d3ee",
      "warning-foreground": "#082f49",
      sidebar: "#07040d",
      "sidebar-accent": "#2e1065",
      "sidebar-border": "#6b21a8",
      "sidebar-ring": "#a3e635",
      "chart-1": "#d946ef",
      "chart-2": "#a3e635",
      "chart-3": "#22d3ee",
      "chart-4": "#c026d3",
      "chart-5": "#f5f3ff",
      "star-gold": "#a3e635",
      "star-gold-foreground": "#14532d",
      "star-gold-muted": "#1a0b2e",
      "surface-warm": "#160b24",
      "rank-cosmic": "#4c1d95",
    },
  },
];

export function getSemanticThemePreset(
  id: SemanticThemePresetId,
): SemanticThemePreset {
  const preset = SEMANTIC_THEME_PRESETS.find((item) => item.id === id);
  if (!preset) throw new Error(`unknown preset: ${id}`);
  return preset;
}

export function semanticTokensEqual(
  left: SemanticTokens,
  right: SemanticTokens,
): boolean {
  for (const key of SEMANTIC_TOKEN_KEYS) {
    if (left[key] !== right[key]) return false;
  }
  return true;
}

export function matchSemanticThemePreset(
  tokens: SemanticTokens,
): SemanticThemePresetId | null {
  for (const preset of SEMANTIC_THEME_PRESETS) {
    if (semanticTokensEqual(tokens, preset.tokens)) {
      return preset.id;
    }
  }
  return null;
}
